<?php

function ironfolio_menu() {

    // admin edit folio list
    $items['admin/ironfolio/%'] = array(
        'title'=>'Iron Folio',
        'description'=>'Edit Iron Folio',
        'page callback' => 'admin_ironfolio',
        'access arguments' => array('administer users'),
        'file' => 'ironfolio.admin.inc',
        'type' => MENU_NORMAL_ITEM
    );
    // frontend folio
    $items['ironfolio/%'] = array(
        'title'=>'Iron Folio Frontend',
        'description'=>'Frontend Iron Folio',
        'page callback' => 'frontend_ironfolio',
        'access callback' => TRUE,
        'file' => 'ironfolio.frontend.inc',
        'type' => MENU_NORMAL_ITEM
    );
    // frontend folio order
    $items['ironfolio/order'] = array(
        'title'=>'Iron Folio Order',
        'description'=>'Frontend Iron Folio Order',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('form_frontend_ironfolio_order'),
        'access callback' => TRUE,
        'file' => 'ironfolio.frontend.order.inc',
        'type' => MENU_NORMAL_ITEM
    );

    return $items;
}

function ironfolio_theme() {
    return array(
        'ironfolio_admin_list' => array(
            'variables' => array('categories' => NULL, 'current_cat_id' => NULL,
                'iron_folio_items' => array(),
                'helper' => NULL),
            'template' => 'ironfolio-admin-list',
        ),
        'ironfolio_frontend_list' => array(
            'variables' => array('categories' => NULL, 'current_cat_id' => NULL,
                'iron_folio_items' => array(),
                'helper' => NULL,
                'pager'  => NULL),
            'template' => 'ironfolio-frontend-list',
        )
    );
}

function ironfolio_preprocess_html(&$variables) {
    drupal_add_css(drupal_get_path('module', 'ironfolio') . '/css/ironfolio.css',
        array('group' => CSS_DEFAULT, 'every_page' => TRUE));
    drupal_add_js(drupal_get_path('module', 'ironfolio') .'/js/ironfolio.js');
}

function ironfolio_node_insert($node) {
    if ($node->type == 'iron_folio') {
        $nodeUpdated = node_load($node->nid);
        $nodeUpdated->field_sort_order['und'][0]['value'] = $node->nid;
        node_save($nodeUpdated);
    }
}
